name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up TeX Live
        uses: latex-actions/setup-texlive@v1
        with:
          texlive-version: 2022
          scheme: full
      - name: Install l3build
        run: tlmgr install l3build
      - name: Build and test LaTeX package
        run: |
          l3build check
          l3build doc
          l3build install
