name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: teatimeguest/setup-texlive-action@v3
        with:
          packages: scheme-full
      - name: Install l3build
        run: tlmgr install l3build
      - name: Build and test LaTeX package
        run: |
          l3build check
          l3build doc
          l3build install
